[package]
name = "my-helloworld-app"
type = "application"
version = "0.1.0"
maintainers = ["Emin Fedar <eminfedar@gmail.com>"]

homepage = "https://pardus.org.tr"
source_repository = "https://github.com/repo-here/if-exists"
keywords = ["package", "tags", "here"]
categories = ["Game", "Education"]

license = "MIT"
architectures = ["any"]

description = """
Multiline description of what this package is about.
"""

[application]
executable = "helloworld"
icon = "helloworld.svg"

[dependencies]
application = []
library = []
