[package]
name = "hello-world"
type = "application"
version = "0.1.0"
maintainers = ["Emin Fedar <eminfedar@gmail.com>"]

homepage = "https://pardus.org.tr"
source_repository = "https://github.com/repo-here/if-exists"
keywords = ["package", "tags", "here"]
categories = ["Game", "Education"]

license = "MIT"
architectures = ["any"]

description = """
Multiline description of what this package is about.
"""

[dependencies.application]
python3 = "3.11"
python3-gi = "3.42"

[dependencies.library]
libgtk4 = "4.8"


[application]
executable = "myapp"
icon = "myapp.svg"