[package]
name = "libhello-world" # library names must started with lib. If not, it will be automatically added.
type = "library"
version = "0.1.0"
maintainers = ["Emin Fedar <eminfedar@gmail.com>"]

homepage = "https://pardus.org.tr"
keywords = ["package", "tags", "here"]
categories = ["Game", "Education"]

license = "MIT"
architectures = ["any"]

description = """
Multiline description of what this package is about.
"""

[dependencies.library]
libgtk4 = "4.8"